In [1]:
import pandas as pd
import os
import glob
import re

**STEP1: CLEANING THE POPULATION OF 2010-2020 (INTERCENSAL) AND 2020-2025 (VINTAGE ESTIMATES) FILES**

**CLEANNING THE DATA FOR "NST-EST2025-POP.xlsx"**

In [5]:
df = pd.read_excel("data_raw/NST-EST2025-POP.xlsx", header=None)

print(df.head(15))
header=2
skiprows=2
df = pd.read_excel(
    "data_raw/NST-EST2025-POP.xlsx",
    skiprows=2
)
print(df.columns)

                                                    0  \
0   table with row headers in column A and column ...
1   Annual Estimates of the Resident Population fo...
2                                     Geographic Area
3                                                 NaN
4                                       United States
5                                           Northeast
6                                             Midwest
7                                               South
8                                                West
9                                            .Alabama
10                                            .Alaska
11                                           .Arizona
12                                          .Arkansas
13                                        .California
14                                          .Colorado

                               1                                   2  \
0                            NaN                                 NaN
1                            NaN                                 NaN
2   April 1, 2020 Estimates Base  Population Estimate (as of July 1)
3                            NaN                                2020
4                      331516113                           331578104
5                       57617560                            57436027
6                       68999462                            68979566
7                      126281605                           126473371
8                       78617486                            78689140
9                        5025437                             5032962
10                        733383                              732906
11                       7158104                             7186647
12                       3011530                             3014399
13                      39555703                            39527808
14                       5775326                             5786873

              3            4            5            6            7
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3        2021.0       2022.0       2023.0       2024.0       2025.0
4   332100166.0  333996304.0  336755052.0  340003797.0  341784857.0
5    57234503.0   57174375.0   57458539.0   57940522.0   58042054.0
6    68867096.0   68872112.0   69132050.0   69518281.0   69762666.0
7   127380165.0  129066102.0  130894372.0  132662072.0  133833983.0
8    78618402.0   78883715.0   79270091.0   79882922.0   80146154.0
9     5050058.0    5076868.0    5117850.0    5163055.0    5193088.0
10     734590.0     733659.0     734654.0     736537.0     737270.0
11    7274022.0    7370065.0    7452073.0    7556424.0    7623818.0
12    3027127.0    3047429.0    3069856.0    3096080.0    3114791.0
13   39152927.0   39125347.0   39181667.0   39364774.0   39355309.0
14    5814368.0    5853355.0    5912240.0    5988502.0    6012561.0
Index(['Geographic Area', 'April 1, 2020 Estimates Base',
       'Population Estimate (as of July 1)', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7'],
      dtype='object')

In [7]:
# Rename
df.columns = [
    "state",
    "base_population",
    "2020",
    "2021",
    "2022",
    "2023",
    "2024",
    "2025"
]

In [9]:
df["state"] = df["state"].str.replace(".", "", regex=False)

In [11]:
population = df.melt(
    id_vars="state",
    value_vars=["2020","2021","2022","2023","2024","2025"],
    var_name="year",
    value_name="population"
)
print(population)

                                                 state  year   population
0                                                  NaN  2020       2020.0
1                                        United States  2020  331578104.0
2                                            Northeast  2020   57436027.0
3                                              Midwest  2020   68979566.0
4                                                South  2020  126473371.0
..                                                 ...   ...          ...
385  The estimates are based on the 2020 Modified A...  2025          NaN
386                                Suggested Citation:  2025          NaN
387  Annual Estimates of the Resident Population fo...  2025          NaN
388      Source: US Census Bureau, Population Division  2025          NaN
389                         Release Date: January 2026  2025          NaN

[390 rows x 3 columns]

In [13]:
print(df.head(15))
print(df.tail(15))

                   state  base_population         2020         2021  \
0                    NaN              NaN       2020.0       2021.0
1          United States      331516113.0  331578104.0  332100166.0
2              Northeast       57617560.0   57436027.0   57234503.0
3                Midwest       68999462.0   68979566.0   68867096.0
4                  South      126281605.0  126473371.0  127380165.0
5                   West       78617486.0   78689140.0   78618402.0
6                Alabama        5025437.0    5032962.0    5050058.0
7                 Alaska         733383.0     732906.0     734590.0
8                Arizona        7158104.0    7186647.0    7274022.0
9               Arkansas        3011530.0    3014399.0    3027127.0
10            California       39555703.0   39527808.0   39152927.0
11              Colorado        5775326.0    5786873.0    5814368.0
12           Connecticut        3607750.0    3579643.0    3607765.0
13              Delaware         989950.0     991890.0    1005130.0
14  District of Columbia         689544.0     670958.0     669637.0

           2022         2023         2024         2025
0        2022.0       2023.0       2024.0       2025.0
1   333996304.0  336755052.0  340003797.0  341784857.0
2    57174375.0   57458539.0   57940522.0   58042054.0
3    68872112.0   69132050.0   69518281.0   69762666.0
4   129066102.0  130894372.0  132662072.0  133833983.0
5    78883715.0   79270091.0   79882922.0   80146154.0
6     5076868.0    5117850.0    5163055.0    5193088.0
7      733659.0     734654.0     736537.0     737270.0
8     7370065.0    7452073.0    7556424.0    7623818.0
9     3047429.0    3069856.0    3096080.0    3114791.0
10   39125347.0   39181667.0   39364774.0   39355309.0
11    5853355.0    5912240.0    5988502.0    6012561.0
12    3618707.0    3641369.0    3674449.0    3688496.0
13    1020279.0    1035354.0    1050123.0    1059952.0
14     674501.0     682559.0     691310.0     693645.0
                                                state  base_population  \
50                                               Utah        3271601.0
51                                            Vermont         643077.0
52                                           Virginia        8631419.0
53                                         Washington        7707519.0
54                                      West Virginia        1793759.0
55                                          Wisconsin        5894323.0
56                                            Wyoming         576872.0
57                                                NaN              NaN
58                                        Puerto Rico        3285874.0
59  The Census Bureau has reviewed this data produ...              NaN
60  The estimates are based on the 2020 Modified A...              NaN
61                                Suggested Citation:              NaN
62  Annual Estimates of the Resident Population fo...              NaN
63      Source: US Census Bureau, Population Division              NaN
64                         Release Date: January 2026              NaN

         2020       2021       2022       2023       2024       2025
50  3283970.0  3339874.0  3393928.0  3449259.0  3502983.0  3538904.0
51   642965.0   647238.0   647614.0   647722.0   646521.0   644663.0
52  8637303.0  8660007.0  8681038.0  8732034.0  8819642.0  8880107.0
53  7726812.0  7744316.0  7786828.0  7838655.0  7927958.0  8001020.0
54  1791670.0  1785921.0  1774003.0  1770036.0  1767402.0  1766147.0
55  5897371.0  5882128.0  5903472.0  5930350.0  5957168.0  5972787.0
56   577669.0   579662.0   581742.0   584666.0   586722.0   588753.0
57        NaN        NaN        NaN        NaN        NaN        NaN
58  3281591.0  3262731.0  3220148.0  3203794.0  3202521.0  3184835.0
59        NaN        NaN        NaN        NaN        NaN        NaN
60        NaN        NaN        NaN        NaN        NaN        NaN
61        NaN        NaN        NaN        NaN        NaN        NaN
62        NaN        NaN        NaN        NaN        NaN        NaN
63        NaN        NaN        NaN        NaN        NaN        NaN
64        NaN        NaN        NaN        NaN        NaN        NaN

In [15]:
#Remove the blank row with " 0 NaN"
population = population.dropna(subset=["state"])
# Remove regions
exclude = [
    "United States",
    "Northeast",
    "Midwest",
    "South",
    "West",
    "Puerto Rico",
    "District of Columbia"
]

population = population[~population["state"].isin(exclude)]
# Remove the notes at the bottom
states = [
    "Alabama","Alaska","Arizona","Arkansas","California","Colorado",
    "Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho",
    "Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana",
    "Maine","Maryland","Massachusetts","Michigan","Minnesota",
    "Mississippi","Missouri","Montana","Nebraska","Nevada",
    "New Hampshire","New Jersey","New Mexico","New York",
    "North Carolina","North Dakota","Ohio","Oklahoma","Oregon",
    "Pennsylvania","Rhode Island","South Carolina","South Dakota",
    "Tennessee","Texas","Utah","Vermont","Virginia","Washington",
    "West Virginia","Wisconsin","Wyoming"
]

population = population[
    population["state"].isin(states)
]

In [17]:
# Convert data types
population["year"] = population["year"].astype(int)
population["population"] = population["population"].astype(int)
# Verify the result
print(population.head())
print(population.shape)

         state  year  population
6      Alabama  2020     5032962
7       Alaska  2020      732906
8      Arizona  2020     7186647
9     Arkansas  2020     3014399
10  California  2020    39527808
(300, 3)

In [19]:
print(population.head(15))
print(population.tail(15))

          state  year  population
6       Alabama  2020     5032962
7        Alaska  2020      732906
8       Arizona  2020     7186647
9      Arkansas  2020     3014399
10   California  2020    39527808
11     Colorado  2020     5786873
12  Connecticut  2020     3579643
13     Delaware  2020      991890
15      Florida  2020    21591325
16      Georgia  2020    10732595
17       Hawaii  2020     1451130
18        Idaho  2020     1849328
19     Illinois  2020    12795348
20      Indiana  2020     6790290
21         Iowa  2020     3191081
              state  year  population
367        Oklahoma  2025     4123288
368          Oregon  2025     4273586
369    Pennsylvania  2025    13059432
370    Rhode Island  2025     1114521
371  South Carolina  2025     5570274
372    South Dakota  2025      935094
373       Tennessee  2025     7315076
374           Texas  2025    31709821
375            Utah  2025     3538904
376         Vermont  2025      644663
377        Virginia  2025     8880107
378      Washington  2025     8001020
379   West Virginia  2025     1766147
380       Wisconsin  2025     5972787
381         Wyoming  2025      588753

In [21]:
#Save the cleaned file
population.to_csv(
    "data_clean/population_2020_2025.csv",
    index=False
)

**CLEANNING THE DATA FOR "nst-est2020int-pop.xlsx"**

In [29]:
# THE SAME PROCESS TO CLEANNING THE DATA FOR "nst-est2020int-pop.xlsx"
df = pd.read_excel("data_raw/nst-est2020int-pop.xlsx", header=None)

print(df.head(15))
header=2
skiprows=2
df = pd.read_excel(
    "data_raw/nst-est2020int-pop.xlsx",
    skiprows=2
)
print(df.columns)

# Rename
df.columns = [
    "state",
    "base_population",
    "2010",
    "2011",
    "2012",
    "2013",
    "2014",
    "2015",
    "2016",
    "2017",
    "2018",
    "2019",
    "2020",
]
df["state"] = df["state"].str.replace(".", "", regex=False)
population = df.melt(
    id_vars="state",
    value_vars=["2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020" ],
    var_name="year",
    value_name="population"
)
print(population)

                                                   0   \
0   table with row headers in column A and column ...
1   Intercensal Estimates of the Resident Populati...
2                                     Geographic Area
3                                                 NaN
4                                       United States
5                                           Northeast
6                                             Midwest
7                                               South
8                                                West
9                                            .Alabama
10                                            .Alaska
11                                           .Arizona
12                                          .Arkansas
13                                        .California
14                                          .Colorado

                              1                                   2   \
0                            NaN                                 NaN
1                            NaN                                 NaN
2   April 1, 2010 Estimates Base  Population Estimate (as of July 1)
3                            NaN                                2010
4                      308758105                           309378227
5                       55318414                            55422736
6                       66929737                            66990957
7                      114563042                           114863745
8                       71946912                            72100789
9                        4780118                             4788095
10                        710246                              714015
11                       6392292                             6401304
12                       2916029                             2921546
13                      37254522                            37322523
14                       5029319                             5046928

             3            4            5            6            7   \
0           NaN          NaN          NaN          NaN          NaN
1           NaN          NaN          NaN          NaN          NaN
2           NaN          NaN          NaN          NaN          NaN
3        2011.0       2012.0       2013.0       2014.0       2015.0
4   311839461.0  314339099.0  316726282.0  319257560.0  321815121.0
5    55818637.0   56161789.0   56460251.0   56737161.0   56936961.0
6    67242411.0   67489449.0   67780382.0   68032120.0   68214912.0
7   115991037.0  117212918.0  118323170.0  119569436.0  120929644.0
8    72787376.0   73474943.0   74162479.0   74918843.0   75733604.0
9     4812576.0    4839947.0    4865253.0    4887757.0    4909177.0
10     722513.0     731106.0     738054.0     737634.0     739120.0
11    6443158.0    6501800.0    6555926.0    6629890.0    6705607.0
12    2938773.0    2948793.0    2954563.0    2961050.0    2970210.0
13   37651212.0   37971412.0   38292557.0   38637421.0   38966939.0
14    5118837.0    5188139.0    5262801.0    5342212.0    5441452.0

             8            9            10           11                    12
0           NaN          NaN          NaN          NaN                   NaN
1           NaN          NaN          NaN          NaN                   NaN
2           NaN          NaN          NaN          NaN  April 1, 2020 Census
3        2016.0       2017.0       2018.0       2019.0                   NaN
4   324353340.0  326608609.0  328529577.0  330226227.0             331449390
5    57116757.0   57304709.0   57474216.0   57560957.0              57609134
6    68410263.0   68615113.0   68780477.0   68920237.0              68985268
7   122277136.0  123445860.0  124461210.0  125475828.0             126266363
8    76549184.0   77242927.0   77813674.0   78269205.0              78588625
9     4931579.0    4953096.0    4977088.0    5003778.0               5024319
10     743397.0     741937.0     737710.0     734820.0                733390
11    6793278.0    6872380.0    6964300.0    7067695.0               7151505
12    2980475.0    2990702.0    2997195.0    3004206.0               3011527
13   39223789.0   39424315.0   39535920.0   39547995.0              39538265
14    5528510.0    5599635.0    5676918.0    5735797.0               5773730
Index(['Geographic Area', 'April 1, 2010 Estimates Base',
       'Population Estimate (as of July 1)', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'April 1, 2020 Census'],
      dtype='object')
                                                 state  year   population
0                                                  NaN  2010       2010.0
1                                        United States  2010  309378227.0
2                                            Northeast  2010   55422736.0
3                                              Midwest  2010   66990957.0
4                                                South  2010  114863745.0
..                                                 ...   ...          ...
710  The April 1, 2010 population estimates base re...  2020          NaN
711                                Suggested Citation:  2020          NaN
712  Intercensal Estimates of the Resident Populati...  2020          NaN
713      Source: US Census Bureau, Population Division  2020          NaN
714                        Release Date: November 2024  2020          NaN

[715 rows x 3 columns]

In [31]:
#Remove the blank row with " 0 NaN"
population = population.dropna(subset=["state"])
# Remove regions
exclude = [
    "United States",
    "Northeast",
    "Midwest",
    "South",
    "West",
    "Puerto Rico",
    "District of Columbia"
]

population = population[~population["state"].isin(exclude)]
# Remove the notes at the bottom
states = [
    "Alabama","Alaska","Arizona","Arkansas","California","Colorado",
    "Connecticut","Delaware","Florida","Georgia","Hawaii","Idaho",
    "Illinois","Indiana","Iowa","Kansas","Kentucky","Louisiana",
    "Maine","Maryland","Massachusetts","Michigan","Minnesota",
    "Mississippi","Missouri","Montana","Nebraska","Nevada",
    "New Hampshire","New Jersey","New Mexico","New York",
    "North Carolina","North Dakota","Ohio","Oklahoma","Oregon",
    "Pennsylvania","Rhode Island","South Carolina","South Dakota",
    "Tennessee","Texas","Utah","Vermont","Virginia","Washington",
    "West Virginia","Wisconsin","Wyoming"
]

population = population[
    population["state"].isin(states)
]

In [33]:
# Convert data types
population["year"] = population["year"].astype(int)
population["population"] = population["population"].astype(int)
# Verify the result
print(population.head())
print(population.shape)

         state  year  population
6      Alabama  2010     4788095
7       Alaska  2010      714015
8      Arizona  2010     6401304
9     Arkansas  2010     2921546
10  California  2010    37322523
(550, 3)

In [35]:
print(population.head(15))
print(population.tail(15))

          state  year  population
6       Alabama  2010     4788095
7        Alaska  2010      714015
8       Arizona  2010     6401304
9      Arkansas  2010     2921546
10   California  2010    37322523
11     Colorado  2010     5046928
12  Connecticut  2010     3580281
13     Delaware  2010      899773
15      Florida  2010    18842405
16      Georgia  2010     9712616
17       Hawaii  2010     1365117
18        Idaho  2010     1571339
19     Illinois  2010    12845460
20      Indiana  2010     6491385
21         Iowa  2010     3051473
              state  year  population
692        Oklahoma  2020     3959353
693          Oregon  2020     4237238
694    Pennsylvania  2020    13002744
695    Rhode Island  2020     1097391
696  South Carolina  2020     5118456
697    South Dakota  2020      886669
698       Tennessee  2020     6910858
699           Texas  2020    29145517
700            Utah  2020     3271601
701         Vermont  2020      643072
702        Virginia  2020     8631410
703      Washington  2020     7705305
704   West Virginia  2020     1793750
705       Wisconsin  2020     5893698
706         Wyoming  2020      576851

In [37]:
# Save the cleaned file "nst-est2020int-pop.xlsx"
population.to_csv(
    "data_clean/population_2010_2020.csv",
    index=False
)

**MERGE THE POPULATION FILES: "NST-EST2025-POP.xlsx" and "nst-est2020int-pop.xlsx"**

In [39]:
# Load the cleaned files
pop1 = pd.read_csv("data_clean/population_2010_2020.csv")
pop2 = pd.read_csv("data_clean/population_2020_2025.csv")

In [41]:
#Check the year ranges
print(pop1["year"].unique())
print(pop2["year"].unique())

[2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]
[2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]

**Both datasets contain data for 2020, creating duplicate records. To eliminate duplicates, I will retain only the 2015–2019 data from population_2010_2020.csv and use all years from population_2020_2025.csv, including 2020–2025.**

In [43]:
# Keep only 2015–2019 from the "population_2010_2020.csv" file
pop1 = pop1[(pop1["year"] >= 2015) & (pop1["year"] <= 2019)]
# Keep all years from the "population_2020_2025.csv" file 
pop2 = pop2[(pop2["year"] >= 2020) & (pop2["year"] <= 2025)]

# Merge the datasets
population = pd.concat([pop1, pop2], ignore_index=True)

# Verify the results after combining the population_2010_2020.csv and population_2020_2025.csv datasets
print(population.shape)

print(population["year"].min())
print(population["year"].max())

(315, 3)
2015
2020

In [98]:
# Sort the data: Sort the records alphabetically by state and chronologically by year within each state
population = population.sort_values(
    by=["state", "year"]
).reset_index(drop=True)

In [45]:
# Verify one state (Texas)
population[population["state"] == "Texas"]

     state  year  population
42   Texas  2015  27394564.0
92   Texas  2016  27825975.0
142  Texas  2017  28188852.0
192  Texas  2018  28508309.0
242  Texas  2019  28856455.0
299  Texas  2020  29145517.0

In [55]:
# Save the final population dataset for the years 2015–2020
# Save the dataset in CSV format
population.to_csv(
    "data_clean/fact_population.csv",
    index=False
)
# Save the dataset in EXCEL format
population.to_excel(
    "data_clean/fact_population.xlsx",
    index=False
)

**STEP 2: CLEAN THE CENSUS STC (TAX REVENUE) DATASET ("census_stc_2015_2020.xlsx")**

The output of the State Tax Collections (STC) will be:

**state | year | tax_type | revenue_amount**

I convert the STC data into this format because it makes the data easier to work with, easier to understand, and easier to use in tools like Power BI to create charts and analysis.

In [57]:
# Load the STC file - "census_stc_2015_2020.xlsx"
stc = pd.read_excel("data_raw/census_stc_2015_2020.xlsx")

# Inspect structure (VERY IMPORTANT)
print(stc.head(10))
print(stc.columns)
print(stc.shape)

     Year  State            Name  FY Ending Date         C105  \
0     NaN    NaN             NaN             NaN  Total Taxes
1  2025.0    0.0  US STATE GOVTS             NaN   1535843715
2  2025.0    1.0   AL STATE GOVT         93025.0     17673064
3  2025.0    2.0   AK STATE GOVT         63025.0      1686939
4  2025.0    3.0   AZ STATE GOVT         63025.0     26635906
5  2025.0    4.0   AR STATE GOVT         63025.0     12560305
6  2025.0    5.0   CA STATE GOVT         63025.0    275041333
7  2025.0    6.0   CO STATE GOVT         63025.0     20261443
8  2025.0    7.0   CT STATE GOVT         63025.0     24753804
9  2025.0    8.0   DE STATE GOVT         63025.0      6949753

                  T01                    C107                        T09  \
0  Property Tax (T01)  Tot Sales & Gr Rec Tax  Total Gen Sales Tax (T09)
1            25476240               697350722                  475228739
2              653667                 8363411                    4815252
3              133795                  335544                          X
4             1431360                17229729                   13506130
5             1622378                 6910963                    5136793
6             3684685                75416611                   53494661
7                   X                 8244700                    4700735
8                   X                 9222486                    6263152
9                   X                  673324                          X

                     C109                           T10  ...  \
0  Total Select Sales Tax  Alcoholic Beverage Tax (T10)  ...
1               222121983                       8330456  ...
2                 3548159                        280517  ...
3                  335544                         39100  ...
4                 3723599                         93486  ...
5                 1774170                         80176  ...
6                21921950                        417149  ...
7                 3543965                         54261  ...
8                 2959334                         75437  ...
9                  673324                         31494  ...

                           T28                        T29                C129  \
0  Occup and Bus Lic NEC (T28)  Other License Taxes (T29)  Total Income Taxes
1                     16246084                    2182487           681127701
2                        71270                          1             7923704
3                        13175                       6940              365420
4                       216776                       2350             7240909
5                       145994                       2066             3380189
6                      3379368                      22854           168110119
7                        66900                          0            11169641
8                        23434                       4650            14720693
9                       184186                      11321             3331906

                           T40                        T41               C130  \
0  Individual Income Tax (T40)  Corp Net Income Tax (T41)  Total Other Taxes
1                    517448442                  163679259           59713771
2                      5799729                    2123975              98283
3                            X                     365420             740920
4                      5490362                    1750547              19283
5                      2735758                     644431             184839
6                    128687029                   39423090           13935433
7                      8815538                    2354103              33099
8                     11219590                    3501103             426524
9                      2754586                     577320             257568

                        T50                           T51  \
0  Death and Gift Tax (T50)  Docum and Stock Tr Tax (T51)
1                   7545196                      13007961
2                         X                         62154
3                         X                             X
4                         0                             X
5                         X                         73397
6                        12                             X
7                         0                             X
8                    130847                        295677
9                         0                        255849

                   T53              T99
0  Severance Tax (T53)  Taxes NEC (T99)
1             19759619         19400995
2                36129                0
3               740920                X
4                19283                X
5                37491            73951
6               176465         13758956
7                33099                X
8                    0                0
9                    X             1719

[10 rows x 37 columns]
Index(['Year', 'State', 'Name', 'FY Ending Date', 'C105', 'T01', 'C107', 'T09',
       'C109', 'T10', 'T11', 'T12', 'T13', 'T14', 'T15', 'T16', 'T18', 'T19',
       'C118', 'T20', 'T21', 'T22', 'T23', 'C123', 'T24', 'T25', 'T27', 'T28',
       'T29', 'C129', 'T40', 'T41', 'C130', 'T50', 'T51', 'T53', 'T99'],
      dtype='object')
(4070, 37)

**This dataset is in a wide format (not a long format), so it needs to be reshaped**

In [59]:
print(stc.columns.tolist())
print(stc.shape)

['Year', 'State', 'Name', 'FY Ending Date', 'C105', 'T01', 'C107', 'T09', 'C109', 'T10', 'T11', 'T12', 'T13', 'T14', 'T15', 'T16', 'T18', 'T19', 'C118', 'T20', 'T21', 'T22', 'T23', 'C123', 'T24', 'T25', 'T27', 'T28', 'T29', 'C129', 'T40', 'T41', 'C130', 'T50', 'T51', 'T53', 'T99']
(4070, 37)

In [61]:
stc = stc[[
    "State",
    "Year",
    "Name",
    "T01",
    "C107",
    "C129",
    "T40",
    "T41"
]]

In [63]:
#Rename columns (make them analytics-friendly)
stc = stc.rename(columns={
    "State": "state",
    "Year": "year",
    "Name": "name",
    "T01": "property_tax",
    "C107": "sales_tax",
    "C129": "income_tax_total",
    "T40": "individual_income_tax",
    "T41": "corporate_income_tax"
})

In [65]:
# Use the appropriate column for text cleaning; the "Name" column should be used to obtain the correct state names.
stc["name"] = stc["name"].astype(str)
stc["name"] = stc["name"].str.replace(" STATE GOVT", "", regex=False)

In [67]:
print(stc.columns.tolist())

['state', 'year', 'name', 'property_tax', 'sales_tax', 'income_tax_total', 'individual_income_tax', 'corporate_income_tax']

In [69]:
# Remove junk rows - # Remove header junk row – “U.S. State Governments and Total Taxes of the U.S.”
stc = stc[stc["year"].notna()]

In [71]:
# Convert year - Only 2015 to 2025
stc = stc.copy()
stc["year"] = pd.to_numeric(stc["year"], errors="coerce")
stc = stc[(stc["year"] >= 2015) & (stc["year"] <= 2025)]

In [73]:
# # Convert numeric columns: "property_tax", "sales_tax", "income_tax_total", "individual_income_tax", "corporate_income_tax"
cols = [
    "property_tax",
    "sales_tax",
    "income_tax_total",
    "individual_income_tax",
    "corporate_income_tax"
]

for col in cols:
    stc[col] = pd.to_numeric(stc[col], errors="coerce").fillna(0)

In [75]:
# Remove US TOTAL row - removes non-state aggregate data
stc = stc[stc["state"] != "US"]

In [77]:
# Replace missing values ("X")
stc = stc.replace("X", 0)

In [79]:
print(stc.head())
print(stc.shape)
print(stc.info())

   state    year name  property_tax  sales_tax  income_tax_total  \
1    0.0  2025.0  USS    25476240.0  697350722       681127701.0
2    1.0  2025.0   AL      653667.0    8363411         7923704.0
3    2.0  2025.0   AK      133795.0     335544          365420.0
4    3.0  2025.0   AZ     1431360.0   17229729         7240909.0
5    4.0  2025.0   AR     1622378.0    6910963         3380189.0

   individual_income_tax  corporate_income_tax
1            517448442.0           163679259.0
2              5799729.0             2123975.0
3                    0.0              365420.0
4              5490362.0             1750547.0
5              2735758.0              644431.0
(561, 8)
<class 'pandas.core.frame.DataFrame'>
Index: 561 entries, 1 to 561
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   state                  561 non-null    float64
 1   year                   561 non-null    float64
 2   name                   561 non-null    object
 3   property_tax           561 non-null    float64
 4   sales_tax              561 non-null    int64
 5   income_tax_total       561 non-null    float64
 6   individual_income_tax  561 non-null    float64
 7   corporate_income_tax   561 non-null    float64
dtypes: float64(6), int64(1), object(1)
memory usage: 39.4+ KB
None

In [81]:
# Convert the year column data type to integer
stc["year"] = stc["year"].astype(int)

In [83]:
# Rename the "Name" column to "State"
stc = stc.rename(columns={"name": "Keep"})

In [85]:
print(stc.head())
print(stc.columns.tolist())
print(stc.shape)

   state  year Keep  property_tax  sales_tax  income_tax_total  \
1    0.0  2025  USS    25476240.0  697350722       681127701.0
2    1.0  2025   AL      653667.0    8363411         7923704.0
3    2.0  2025   AK      133795.0     335544          365420.0
4    3.0  2025   AZ     1431360.0   17229729         7240909.0
5    4.0  2025   AR     1622378.0    6910963         3380189.0

   individual_income_tax  corporate_income_tax
1            517448442.0           163679259.0
2              5799729.0             2123975.0
3                    0.0              365420.0
4              5490362.0             1750547.0
5              2735758.0              644431.0
['state', 'year', 'Keep', 'property_tax', 'sales_tax', 'income_tax_total', 'individual_income_tax', 'corporate_income_tax']
(561, 8)

In [87]:
# Drop numeric state column first (the bad one)
stc = stc.drop(columns=["state"])

In [89]:
print(stc.head())
print(stc.columns.tolist())
print(stc.shape)

   year Keep  property_tax  sales_tax  income_tax_total  \
1  2025  USS    25476240.0  697350722       681127701.0
2  2025   AL      653667.0    8363411         7923704.0
3  2025   AK      133795.0     335544          365420.0
4  2025   AZ     1431360.0   17229729         7240909.0
5  2025   AR     1622378.0    6910963         3380189.0

   individual_income_tax  corporate_income_tax
1            517448442.0           163679259.0
2              5799729.0             2123975.0
3                    0.0              365420.0
4              5490362.0             1750547.0
5              2735758.0              644431.0
['year', 'Keep', 'property_tax', 'sales_tax', 'income_tax_total', 'individual_income_tax', 'corporate_income_tax']
(561, 7)

In [91]:
# Rename name → state
stc = stc.rename(columns={"Keep": "state"})

In [93]:
print(stc.head())
print(stc.columns.tolist())
print(stc.shape)

   year state  property_tax  sales_tax  income_tax_total  \
1  2025   USS    25476240.0  697350722       681127701.0
2  2025    AL      653667.0    8363411         7923704.0
3  2025    AK      133795.0     335544          365420.0
4  2025    AZ     1431360.0   17229729         7240909.0
5  2025    AR     1622378.0    6910963         3380189.0

   individual_income_tax  corporate_income_tax
1            517448442.0           163679259.0
2              5799729.0             2123975.0
3                    0.0              365420.0
4              5490362.0             1750547.0
5              2735758.0              644431.0
['year', 'state', 'property_tax', 'sales_tax', 'income_tax_total', 'individual_income_tax', 'corporate_income_tax']
(561, 7)

In [95]:
# Swap only two columns (year ↔ state)
cols = stc.columns.tolist()

# swap year and state
i_year = cols.index("year")
i_state = cols.index("state")

cols[i_year], cols[i_state] = cols[i_state], cols[i_year]

stc = stc[cols]

In [97]:
print(stc.head())
print(stc.columns.tolist())
print(stc.shape)

  state  year  property_tax  sales_tax  income_tax_total  \
1   USS  2025    25476240.0  697350722       681127701.0
2    AL  2025      653667.0    8363411         7923704.0
3    AK  2025      133795.0     335544          365420.0
4    AZ  2025     1431360.0   17229729         7240909.0
5    AR  2025     1622378.0    6910963         3380189.0

   individual_income_tax  corporate_income_tax
1            517448442.0           163679259.0
2              5799729.0             2123975.0
3                    0.0              365420.0
4              5490362.0             1750547.0
5              2735758.0              644431.0
['state', 'year', 'property_tax', 'sales_tax', 'income_tax_total', 'individual_income_tax', 'corporate_income_tax']
(561, 7)

In [99]:
# REMOVE NON-STATE ROWS: To avoid mixing the U.S. total with individual states, per capita calculations becoming incorrect, and Power BI maps breaking.
stc = stc[stc["state"] != "USS"]

In [101]:
# RESET INDEX
stc = stc.reset_index(drop=True)

In [103]:
# VERIFY CLEAN DATA
print(stc["state"].unique()[:10])
print(stc.shape)

['AL' 'AK' 'AZ' 'AR' 'CA' 'CO' 'CT' 'DE' 'FL' 'GA']
(550, 7)

In [105]:
# Check duplicate state-year rows
stc.duplicated(subset=["state", "year"]).sum()

0

**After data cleaning, I will create the Total Tax KPI**

In [107]:
# Create Total Tax KPI
stc["total_tax"] = (
    stc["property_tax"] +
    stc["sales_tax"] +
    stc["income_tax_total"]
)

In [109]:
print(stc.head())
print(stc.columns.tolist())
print(stc.shape)

  state  year  property_tax  sales_tax  income_tax_total  \
0    AL  2025      653667.0    8363411         7923704.0
1    AK  2025      133795.0     335544          365420.0
2    AZ  2025     1431360.0   17229729         7240909.0
3    AR  2025     1622378.0    6910963         3380189.0
4    CA  2025     3684685.0   75416611       168110119.0

   individual_income_tax  corporate_income_tax    total_tax
0              5799729.0             2123975.0   16940782.0
1                    0.0              365420.0     834759.0
2              5490362.0             1750547.0   25901998.0
3              2735758.0              644431.0   11913530.0
4            128687029.0            39423090.0  247211415.0
['state', 'year', 'property_tax', 'sales_tax', 'income_tax_total', 'individual_income_tax', 'corporate_income_tax', 'total_tax']
(550, 8)

In [111]:
# Convert abbreviations to full names
state_map = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming"
}

stc["state"] = stc["state"].map(state_map)

In [113]:
# Verify the conversion
print(stc["state"].head())
print(stc["state"].unique()[:10])

0       Alabama
1        Alaska
2       Arizona
3      Arkansas
4    California
Name: state, dtype: object
['Alabama' 'Alaska' 'Arizona' 'Arkansas' 'California' 'Colorado'
 'Connecticut' 'Delaware' 'Florida' 'Georgia']

In [115]:
#  Save the cleaned STC data
stc.to_csv("data_clean/fact_tax_revenue.csv", index=False)

**CLEANING THE 'qtax_20xx_qxx' EXCEL FILES**

In [1]:
import xlrd
print("xlrd is working!")

xlrd is working!

In [2]:
# Convert ALL 26 files (.xls → .xlsx)
# Get all .xls files
import pandas as pd
import glob

files = glob.glob("data_raw/*.xls")

for file in files:
    df = pd.read_excel(file, engine="xlrd")

    new_file = file.replace(".xls", ".xlsx")

    df.to_excel(new_file, index=False, engine="openpyxl")

print("All files converted successfully!")

All files converted successfully!

In [3]:
xlsx_files = glob.glob("data_raw/*.xlsx")
print(len(xlsx_files))
print(xlsx_files[:5])

51
['data_raw\\2025 Sales Tax Rates as of July 1, 2025.xlsx', 'data_raw\\2025 State Corporate Income Tax Rates  Brackets.xlsx', 'data_raw\\2025-State-Individual-Income-Tax-Rates-and-Brackets-2025.xlsx', 'data_raw\\census_stc_2015_2020.xlsx', 'data_raw\\nst-est2020int-pop.xlsx']

In [73]:
# Create a separate folder for converted files
os.makedirs("data_converted", exist_ok=True)

# Re-run conversion properly
files = glob.glob("data_raw/*.xls")

for file in files:
    df = pd.read_excel(file, engine="xlrd")

    base_name = os.path.basename(file).replace(".xls", ".xlsx")
    new_file = os.path.join("data_converted", base_name)

    df.to_excel(new_file, index=False, engine="openpyxl")

print("Only 26 files converted into data_converted folder!")

Only 26 files converted into data_converted folder!

In [265]:
# Load the QTAX file - "qtax_2015_q1.xls"
qtax = pd.read_excel("data_converted/qtax_2015_q1.xlsx")

In [267]:
df = pd.read_excel(
    "data_converted/qtax_2015_q1.xlsx",
    header=5
)

print(df.head())
print(df.columns)

                                 Tax Description Code  Unnamed: 2  \
0                                    Total Taxes  NaN         NaN
1                                 Property taxes  T01         NaN
2                 Sales and gross receipts taxes  NaN         NaN
3               General sales and gross receipts  T09         NaN
4       Selective sales and gross receipts taxes  NaN         NaN

   U.S. Total (excludes Washington, D.C.)  Unnamed: 4  Alabama  Unnamed: 6  \
0                             219860136.0         NaN  2391533         NaN
1                               3507189.0         NaN   172259         NaN
2                                     NaN         NaN      NaN         NaN
3                              68648287.0         NaN   587045         NaN
4                                     NaN         NaN      NaN         NaN

  Alaska  Unnamed: 8  Arizona  ...  Unnamed: 96  Washington  Unnamed: 98  \
0  54472         NaN  3027273  ...          NaN     5417126          NaN
1     22         NaN   220661  ...          NaN      902874          NaN
2    NaN         NaN      NaN  ...          NaN         NaN          NaN
3      X         NaN  1547895  ...          NaN     3091697          NaN
4    NaN         NaN      NaN  ...          NaN         NaN          NaN

  West Virginia  Unnamed: 100  Wisconsin  Unnamed: 102 Wyoming  Unnamed: 104  \
0       1273869           NaN  3815780.0           NaN  554223           NaN
1          1158           NaN    60921.0           NaN   33191           NaN
2           NaN           NaN        NaN           NaN     NaN           NaN
3        322565           NaN  1141053.0           NaN  200031           NaN
4           NaN           NaN        NaN           NaN     NaN           NaN

  Washington, D.C.
0          1710036
1           596035
2              NaN
3           270033
4              NaN

[5 rows x 106 columns]
Index(['Tax Description', 'Code', 'Unnamed: 2',
       'U.S. Total (excludes Washington, D.C.)', 'Unnamed: 4', 'Alabama',
       'Unnamed: 6', 'Alaska', 'Unnamed: 8', 'Arizona',
       ...
       'Unnamed: 96', 'Washington', 'Unnamed: 98', 'West Virginia',
       'Unnamed: 100', 'Wisconsin', 'Unnamed: 102', 'Wyoming', 'Unnamed: 104',
       'Washington, D.C.'],
      dtype='object', length=106)

In [269]:
# Drop all "Unnamed" columns (important)
df = df.loc[:, ~df.columns.str.contains("^Unnamed")]

In [271]:
# Clean column list
print(df.columns.tolist())

['Tax Description', 'Code', 'U.S. Total (excludes Washington, D.C.)', 'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington', 'West Virginia', 'Wisconsin', 'Wyoming', 'Washington, D.C.']

In [273]:
# Fix numeric values (optional but recommended)
cols = df.columns.drop(["Tax Description", "Code"])

df[cols] = df[cols].apply(pd.to_numeric, errors="coerce")

In [275]:
# Reshape to long format (useful for dashboards)
df_long = df.melt(
    id_vars=["Tax Description", "Code"],
    var_name="State",
    value_name="Tax_Value"
)

print(df_long.head())

                                 Tax Description Code  \
0                                    Total Taxes  NaN
1                                 Property taxes  T01
2                 Sales and gross receipts taxes  NaN
3               General sales and gross receipts  T09
4       Selective sales and gross receipts taxes  NaN

                                    State    Tax_Value
0  U.S. Total (excludes Washington, D.C.)  219860136.0
1  U.S. Total (excludes Washington, D.C.)    3507189.0
2  U.S. Total (excludes Washington, D.C.)          NaN
3  U.S. Total (excludes Washington, D.C.)   68648287.0
4  U.S. Total (excludes Washington, D.C.)          NaN

In [277]:
# remove U.S. Total column
state_cols = [
    col for col in state_cols
    if "U.S. Total" not in col
]

In [279]:
# Remove the non-state columns
# identify real state columns
id_vars = ["Tax Description", "Code"]

state_cols = [col for col in df.columns if col not in id_vars]
print(state_cols[:10])

# melt again to get the long table format

df_long = df.melt(
    id_vars=["Tax Description", "Code"],
    value_vars=state_cols,
    var_name="State",
    value_name="Tax_Value"
)

print(df_long.head())

['U.S. Total (excludes Washington, D.C.)', 'Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida']
                                 Tax Description Code  \
0                                    Total Taxes  NaN
1                                 Property taxes  T01
2                 Sales and gross receipts taxes  NaN
3               General sales and gross receipts  T09
4       Selective sales and gross receipts taxes  NaN

                                    State    Tax_Value
0  U.S. Total (excludes Washington, D.C.)  219860136.0
1  U.S. Total (excludes Washington, D.C.)    3507189.0
2  U.S. Total (excludes Washington, D.C.)          NaN
3  U.S. Total (excludes Washington, D.C.)   68648287.0
4  U.S. Total (excludes Washington, D.C.)          NaN

In [281]:
keep_taxes = [
    "Property taxes",
    #"Sales and gross receipts taxes",
    "General sales and gross receipts",
    #"Selective sales and gross receipts taxes",
    "Individual income",
    "Individual income taxes",
    "Corporation net income",
    "Corporate income taxes"
]

In [283]:
df_long_clean["Tax_Group"] = df_long_clean["Tax Description"].replace({
    "Property taxes": "Property Tax",
    "General sales and gross receipts": "Sales Tax",
    "Individual income": "Individual Income Tax",
    "Corporation net income": "Corporate Income Tax"
})

In [285]:
df_long["Tax Description"] = df_long["Tax Description"].str.replace("\xa0", "", regex=True).str.strip()

In [287]:
df_final = df_long_clean.pivot_table(
    index="State",
    columns="Tax_Group",
    values="Tax_Value",
    aggfunc="sum"
).reset_index()

In [289]:
df_long_clean = df_long[
    df_long["Tax Description"].isin(keep_taxes)
].copy()

In [291]:
df_long_clean["Tax_Group"] = df_long_clean["Tax Description"].replace({
    "Property taxes": "Property Tax",

    "General sales and gross receipts taxes": "Sales Tax",
    "Selective sales and gross receipts taxes": "Sales Tax",
    "Sales and gross receipts taxes": "Sales Tax",

    "Individual income taxes": "Individual Income Tax",
    "Individual income": "Individual Income Tax",
    
    "Corporation net income": "Corporate Income Tax",
    "Corporate income taxes": "Corporate Income Tax"
})

In [293]:
# rename column properly ( General sales and gross receipts taxes to Sales Tax)
df_final = df_final.rename(columns={
    "General sales and gross receipts": "Sales Tax"
})

In [295]:
df_final = df_long_clean.pivot_table(
    index="State",
    columns="Tax_Group",
    values="Tax_Value",
    aggfunc="sum"
).reset_index()

In [297]:
#df_final["total_tax"] = (
   # df_final["Property Tax"] +
    #df_final["Sales Tax"] +
    #df_final["Individual Income Tax"] +
    #df_final["Corporate Income Tax"]
#)

In [299]:
print(df_final.columns.tolist())

['State', 'Corporate Income Tax', 'General sales and gross receipts', 'Individual Income Tax', 'Property Tax']

In [301]:
print(df_final.columns.tolist())
df_final.head(10)

['State', 'Corporate Income Tax', 'General sales and gross receipts', 'Individual Income Tax', 'Property Tax']

Tax_Group,State,Corporate Income Tax,General sales and gross receipts,Individual Income Tax,Property Tax
0,Alabama,102226.0,587045.0,808020.0,172259.0
1,Alaska,-38989.0,0.0,0.0,22.0
2,Arizona,96624.0,1547895.0,605407.0,220661.0
3,Arkansas,107234.0,797183.0,497294.0,79912.0
4,California,1835098.0,9576402.0,17731008.0,592158.0
5,Colorado,96889.0,715935.0,1350349.0,0.0
6,Connecticut,210769.0,1009674.0,1930546.0,0.0
7,Delaware,42530.0,0.0,380825.0,0.0
8,Florida,457320.0,5528697.0,0.0,20.0
9,Georgia,256495.0,1323617.0,1896330.0,214359.0

In [303]:
# Add time info (Quater and year)
df_long["Year"] = 2015
df_long["Quarter"] = "Q1"

In [305]:
print(df_final.columns.tolist())
df_final.head(10)

['State', 'Corporate Income Tax', 'General sales and gross receipts', 'Individual Income Tax', 'Property Tax']

Tax_Group,State,Corporate Income Tax,General sales and gross receipts,Individual Income Tax,Property Tax
0,Alabama,102226.0,587045.0,808020.0,172259.0
1,Alaska,-38989.0,0.0,0.0,22.0
2,Arizona,96624.0,1547895.0,605407.0,220661.0
3,Arkansas,107234.0,797183.0,497294.0,79912.0
4,California,1835098.0,9576402.0,17731008.0,592158.0
5,Colorado,96889.0,715935.0,1350349.0,0.0
6,Connecticut,210769.0,1009674.0,1930546.0,0.0
7,Delaware,42530.0,0.0,380825.0,0.0
8,Florida,457320.0,5528697.0,0.0,20.0
9,Georgia,256495.0,1323617.0,1896330.0,214359.0

In [261]:
output_file = "data_clean/qtax_2015_q1_clean.csv"

df_final.to_csv(output_file, index=False)

print(f"Saved to: {output_file}")

Saved to: data_clean/qtax_2015_q1_clean.csv

**DEVELOP AN AUTOMATED PROCESS TO CLEAN THE REMAINING 26 EXCEL FILES**

In [315]:
import os
import re
import glob
import pandas as pd

# Create output folder
os.makedirs("data_cleaned", exist_ok=True)

# Get all QTAX files
files = sorted(glob.glob("data_converted/qtax_*.xlsx"))

for file in files:

    print(f"Processing {os.path.basename(file)}...")

    # -----------------------------
    # Extract year and quarter
    # -----------------------------
    match = re.search(r"qtax_(\d{4})_(q\d)\.xlsx", os.path.basename(file), re.IGNORECASE)

    year = int(match.group(1))
    quarter = match.group(2).upper()

    # -----------------------------
    # Read Excel
    # -----------------------------
    df = pd.read_excel(file, header=5)

    # Remove unnamed columns
    df = df.loc[:, ~df.columns.str.contains("^Unnamed")]

    # Convert values to numeric
    value_cols = df.columns.drop(["Tax Description", "Code"])
    df[value_cols] = df[value_cols].apply(pd.to_numeric, errors="coerce")

    # -----------------------------
    # Reshape to long format
    # -----------------------------
    state_cols = [
        c for c in value_cols
        if "U.S. Total" not in c
    ]

    df_long = df.melt(
        id_vars=["Tax Description", "Code"],
        value_vars=state_cols,
        var_name="State",
        value_name="Tax_Value"
    )

    # Clean tax description
    df_long["Tax Description"] = (
        df_long["Tax Description"]
        .str.replace("\xa0", "", regex=True)
        .str.strip()
    )

    # -----------------------------
    # Keep only desired taxes
    # -----------------------------
    keep_taxes = [
        "Property taxes",
        "General sales and gross receipts",
        "Individual income",
        "Individual income taxes",
        "Corporation net income",
        "Corporate income taxes"
    ]

    df_long_clean = df_long[
        df_long["Tax Description"].isin(keep_taxes)
    ].copy()

    # Standardize tax names
    df_long_clean["Tax_Group"] = df_long_clean["Tax Description"].replace({
        "Property taxes": "Property Tax",
        "General sales and gross receipts": "Sales Tax",
        "Individual income": "Individual Income Tax",
        "Individual income taxes": "Individual Income Tax",
        "Corporation net income": "Corporate Income Tax",
        "Corporate income taxes": "Corporate Income Tax"
    })

    # -----------------------------
    # Pivot to final format
    # -----------------------------
    df_final = (
        df_long_clean
        .pivot_table(
            index="State",
            columns="Tax_Group",
            values="Tax_Value",
            aggfunc="sum"
        )
        .reset_index()
    )

    # Ensure all expected columns exist
    expected_cols = [
        "Property Tax",
        "Sales Tax",
        "Individual Income Tax",
        "Corporate Income Tax"
    ]

    for col in expected_cols:
        if col not in df_final.columns:
            df_final[col] = 0

    # Add year and quarter
    df_final["Year"] = year
    df_final["Quarter"] = quarter

    # Total tax
    df_final["Total Tax"] = (
        df_final["Property Tax"] +
        df_final["Sales Tax"] +
        df_final["Individual Income Tax"] +
        df_final["Corporate Income Tax"]
    )

    # Arrange columns
    df_final = df_final[
        [
            "State",
            "Year",
            "Quarter",
            "Property Tax",
            "Sales Tax",
            "Individual Income Tax",
            "Corporate Income Tax",
            "Total Tax"
        ]
    ]

    # -----------------------------
    # Save cleaned file
    # -----------------------------
    output_file = os.path.join(
    "data_cleaned",
    os.path.basename(file).replace(".xlsx", "_clean.csv")
)

    df_final.to_csv(output_file, index=False)

print("\nAll files have been processed successfully!")

Processing qtax_2015_q1.xlsx...
Processing qtax_2015_q2.xlsx...
Processing qtax_2015_q3.xlsx...
Processing qtax_2015_q4.xlsx...
Processing qtax_2016_q1.xlsx...
Processing qtax_2016_q2.xlsx...
Processing qtax_2016_q3.xlsx...
Processing qtax_2016_q4.xlsx...
Processing qtax_2017_q1.xlsx...
Processing qtax_2017_q2.xlsx...
Processing qtax_2017_q3.xlsx...
Processing qtax_2017_q4.xlsx...
Processing qtax_2018_q1.xlsx...
Processing qtax_2018_q2.xlsx...
Processing qtax_2018_q3.xlsx...
Processing qtax_2018_q4.xlsx...
Processing qtax_2019_q1.xlsx...
Processing qtax_2019_q2.xlsx...
Processing qtax_2019_q3.xlsx...
Processing qtax_2019_q4.xlsx...
Processing qtax_2020_q1.xlsx...
Processing qtax_2020_q2.xlsx...
Processing qtax_2020_q3.xlsx...
Processing qtax_2020_q4.xlsx...
Processing qtax_2021_q1.xlsx...
Processing qtax_2021_q2.xlsx...

All files have been processed successfully!